name: "aarch64-linux (qemu)"
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: docker/setup-qemu-action@v1
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'NixOS/nixpkgs'
        path: 'nixpkgs'
        ref: 'master'
        filter: 'blob:none'
    - uses: cachix/install-nix-action@fc6e360bedc9ee72d75e701397f0bb30dce77568 # v31
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        install_url: https://releases.nixos.org/nix/nix-2.30.2/install
        extra_nix_config: "experimental-features = nix-command flakes fetch-closure"
    - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
    - run: ./build.sh --dry-run --system aarch64-linux || true
    - run: ./build.sh ' ' --system aarch64-linux
