name: "build for aarch64-darwin"
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: douglascamata/setup-docker-macos-action@v1-alpha
    - uses: docker/setup-qemu-action@v1
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'NixOS/nixpkgs'
        path: 'nixpkgs'
        ref: 'master'
        fetch-depth: 0
        filter: 'blob:none'
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        install_url: https://releases.nixos.org/nix/nix-2.18.1/install
        extra_nix_config: "experimental-features = nix-command flakes fetch-closure"
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: ./build.sh --dry-run --system aarch64-darwin || true
    - run: ./build.sh ' ' --system aarch64-darwin
