name: "build cache"
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: docker/setup-qemu-action@v1
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        install_url: https://releases.nixos.org/nix/nix-2.18.1/install
        extra_nix_config: "experimental-features = nix-command flakes fetch-closure"
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: ./build.sh --extra-platforms aarch64-linux --dry-run
    - run: ./build.sh --extra-platforms aarch64-linux
