name: "build cache"
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        install_url: https://releases.nixos.org/nix/nix-2.17.0/install
        extra_nix_config: "experimental-features = nix-command flakes fetch-closure"
    - run: ./build.sh
